### ISSUE TITLE
Avoid values with hyphens 

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/diracx-charts#83]
We have quite a few values (e.g `init-sql`) which use hyphens while it is bad practice and requires some gymnastic to manipulate (e.g. `index .Values "init-sql" "enabled"`)

https://helm.sh/docs/chart_best_practices/values/#naming-conventions

**Comment by lipika-27** [comment]
Hi @chaen,
I am interested in contributing to resolving this issue and am open to collaboration. If there are any specific guidelines or preferences, please let me know.

**Comment by chaen** [comment]
Hi @lipika-27 and thanks for your interest.
This is a quite straight forward task, and the guideline is really just the doc I've linked in the issue description.
Basically remove all the hyphen words in the `values.yaml` with camel case (e.g. `init-sql` -> `initSql`)

**Comment by lipika-27** [comment]
Thanks @chaen,
I will start working on this.
