### ISSUE TITLE
readlink -f in run_demo.sh

### ISSUE THREAD

**Issue by atsareg** [DIRACGrid/diracx-charts#9]
The use of readlink -f in run_demo.sh is not working on MacOS. The extract from the man readlink:

```
When invoked as readlink, only the target of the symbolic link is printed.  
If the given argument is not a symbolic link, readlink will print nothing and 
exit with an error.
```
  and -f flag is not allowed for readlink

**Comment by chrisburr** [comment]
I think the script should be portable across any reasonable macOS and Linux machine once #29 is merged so I'll close this.
